export const students = [
    { id: 1, name: 'Jhon Doe', subject: 'Biology', grade: 98, passed: true },
    { id: 2, name: 'Emily Clark', subject: 'Mathematics', grade: 87, passed: true },
    { id: 3, name: 'Michael Smith', subject: 'Physics', grade: 92, passed: true },
    { id: 4, name: 'Sarah Johnson', subject: 'Chemistry', grade: 76, passed: true },
    { id: 5, name: 'David Lee', subject: 'English', grade: 33, passed: false },
    { id: 6, name: 'Olivia Brown', subject: 'History', grade: 81, passed: true },
    { id: 7, name: 'James Wilson', subject: 'Geography', grade: 90, passed: true },
    { id: 8, name: 'Sophia Davis', subject: 'Computer Science', grade: 95, passed: true },
    { id: 9, name: 'Daniel Miller', subject: 'Biology', grade: 62, passed: true },
    { id: 10, name: 'Ava Garcia', subject: 'Mathematics', grade: 29, passed: false },
    { id: 11, name: 'Ryan Martinez', subject: 'Physics', grade: 71, passed: true },
    { id: 12, name: 'Grace Anderson', subject: 'Chemistry', grade: 85, passed: true },
    { id: 13, name: 'Ethan Thomas', subject: 'English', grade: 93, passed: true },
    { id: 14, name: 'Chloe Jackson', subject: 'History', grade: 58, passed: true },
    { id: 15, name: 'Matthew White', subject: 'Geography', grade: 77, passed: true },
    { id: 16, name: 'Isabella Harris', subject: 'Computer Science', grade: 99, passed: true },
    { id: 17, name: 'Andrew Martin', subject: 'Biology', grade: 66, passed: true },
    { id: 18, name: 'Mia Thompson', subject: 'Mathematics', grade: 89, passed: true },
    { id: 19, name: 'Joshua Robinson', subject: 'Physics', grade: 54, passed: true },
    { id: 20, name: 'Ella Walker', subject: 'Chemistry', grade: 97, passed: true },
    { id: 21, name: 'Christopher Hall', subject: 'English', grade: 38, passed: false },
    { id: 22, name: 'Zoe Allen', subject: 'History', grade: 83, passed: true },
    { id: 23, name: 'Nathan Young', subject: 'Geography', grade: 91, passed: true },
    { id: 24, name: 'Lily King', subject: 'Computer Science', grade: 73, passed: true },
    { id: 25, name: 'Benjamin Wright', subject: 'Biology', grade: 87, passed: true },
];