export const bollywoodMovies = [
    {
        id: 1,
        title: "Jism",
        rating: 5.3,
        genre: "Romance/Thriller",
        year: 2003,
        certification: "A",
        director: "Amit Saxena",
        cast: ["John Abraham", "Bipasha Basu"],
        isFavorite: false,
        image: "https://picsum.photos/300/450?random=18"
    },
    {
        id: 2,
        title: "Murder",
        rating: 6.8,
        genre: "Thriller/Romance",
        year: 2004,
        certification: "A",
        director: "Anurag Basu",
        cast: ["Emraan Hashmi", "Mallika Sherawat"],
        isFavorite: false,
        image: "https://picsum.photos/300/450?random=19"
    },
    {
        id: 3,
        title: "Murder 2",
        rating: 6.3,
        genre: "Thriller",
        year: 2011,
        certification: "A",
        director: "Mohit Suri",
        cast: ["Emraan Hashmi", "Jacqueline Fernandez"],
        isFavorite: false,
        image: "https://picsum.photos/300/450?random=20"
    },
    {
        id: 4,
        title: "Hate Story",
        rating: 5.4,
        genre: "Thriller",
        year: 2012,
        certification: "A",
        director: "Vivek Agnihotri",
        cast: ["Paoli Dam", "Gulshan Devaiya"],
        isFavorite: false,
        image: "https://imgs.search.brave.com/TnPd2kG01I69mv-DMwdlfoi4Vh1cklX6dW5JMHGLSvA/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL00v/TVY1Qk4yVTVZMkkx/WVRNdE16aGlaQzAw/WkdObUxXRTNZMkl0/TVRSbE9XUTBOV1F6/T1RZMVhrRXlYa0Zx/Y0djQC5qcGc"
    },
    {
        id: 5,
        title: "Hate Story 2",
        rating: 4.8,
        genre: "Thriller",
        year: 2014,
        certification: "A",
        director: "Vishal Pandya",
        cast: ["Surveen Chawla", "Sushant Singh"],
        isFavorite: false,
        image: "https://imgs.search.brave.com/GeyAZxj5KuBIiv4TW3j3tqjlqDhiol3qMT3DnZO5YPw/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9yZXNp/emUuaW5kaWF0dm5l/d3MuY29tL2VuL3Jl/c2l6ZS9vbGRidWNr/ZXQvMTIwMF8tL2Vu/dGVydGFpbm1lbnRi/b2xseXdvb2QvSGF0/ZS1TdG9yeS1tb3Zp/MTU3MjIuanBn"
    },
    {
        id: 6,
        title: "Ragini MMS",
        rating: 5.1,
        genre: "Horror",
        year: 2011,
        certification: "A",
        director: "Pawan Kripalani",
        cast: ["Kainaz Motivala", "Rajkummar Rao"],
        isFavorite: false,
        image: "https://picsum.photos/300/450?random=23"
    },
    {
        id: 7,
        title: "Ragini MMS 2",
        rating: 4.0,
        genre: "Horror",
        year: 2014,
        certification: "A",
        director: "Bhushan Patel",
        cast: ["Sunny Leone", "Parvin Dabas"],
        isFavorite: false,
        image: "https://picsum.photos/300/450?random=24"
    },
    {
        id: 8,
        title: "Julie",
        rating: 5.5,
        genre: "Drama",
        year: 2004,
        certification: "A",
        director: "Deepak Shivdasani",
        cast: ["Neha Dhupia", "Priyanshu Chatterjee"],
        isFavorite: false,
        image: "https://picsum.photos/300/450?random=25"
    },
    {
        id: 9,
        title: "Chhichhore",
        rating: 8.3,
        genre: "Comedy/Drama",
        year: 2019,
        certification: "UA",
        director: "Nitesh Tiwari",
        cast: ["Sushant Singh Rajput", "Shraddha Kapoor"],
        isFavorite: false,
        image: "https://imgs.search.brave.com/vApTGP8mhJLVqMC-8P5OtaAzZwpq7hGK4K9nw9Cut_c/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9jLnNh/YXZuY2RuLmNvbS85/MzcvQ2hoaWNoaG9y/ZS1IaW5kaS0yMDE5/LTIwMTkwOTA0MTA0/MDIzLTUwMHg1MDAu/anBn"
    },
    {
        id: 10,
        title: "3 Idiots",
        rating: 9.2,
        genre: "Comedy/Drama",
        year: 2009,
        certification: "U",
        director: "Rajkumar Hirani",
        cast: ["Aamir Khan", "R. Madhavan", "Sharman Joshi"],
        isFavorite: false,
        image: "https://shorturl.at/FWrBL"
    },
    {
        id: 11,
        title: "Dangal",
        rating: 8.8,
        genre: "Biography/Sports",
        year: 2016,
        certification: "U",
        director: "Nitesh Tiwari",
        cast: ["Aamir Khan", "Fatima Sana Shaikh"],
        isFavorite: false,
        image: "https://imgs.search.brave.com/_VkOZNNTTqFjnzuJ-47JajFIR7O9GY-gm3CppIxNSWU/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pbWcu/bm93cnVubmluZy5j/b20vY29udGVudC9t/b3ZpZS8yMDE2L0Rh/bmdhbC9iZzIyLmpw/Zw"
    },
    {
        id: 12,
        title: "PK",
        rating: 8.2,
        genre: "Comedy/Drama",
        year: 2014,
        certification: "UA",
        director: "Rajkumar Hirani",
        cast: ["Aamir Khan", "Anushka Sharma"],
        isFavorite: false,
        image: "https://picsum.photos/300/450?random=4"
    },
    {
        id: 13,
        title: "Zindagi Na Milegi Dobara",
        rating: 8.6,
        genre: "Adventure/Drama",
        year: 2011,
        certification: "U",
        director: "Zoya Akhtar",
        cast: ["Hrithik Roshan", "Farhan Akhtar"],
        isFavorite: false,
        image: "https://picsum.photos/300/450?random=5"
    },
    {
        id: 14,
        title: "War",
        rating: 7.4,
        genre: "Action/Thriller",
        year: 2019,
        certification: "UA",
        director: "Siddharth Anand",
        cast: ["Hrithik Roshan", "Tiger Shroff"],
        isFavorite: false,
        image: "https://picsum.photos/300/450?random=6"
    },
    {
        id: 15,
        title: "Pathaan",
        rating: 7.8,
        genre: "Action/Thriller",
        year: 2023,
        certification: "UA",
        director: "Siddharth Anand",
        cast: ["Shah Rukh Khan", "Deepika Padukone"],
        isFavorite: false,
        image: "https://picsum.photos/300/450?random=7"
    },
    {
        id: 16,
        title: "Jawan",
        rating: 8.0,
        genre: "Action/Drama",
        year: 2023,
        certification: "UA",
        director: "Atlee",
        cast: ["Shah Rukh Khan", "Nayanthara"],
        isFavorite: false,
        image: "https://imgs.search.brave.com/gJo3RjVYX1ZYuBe8UIN0T7sMpvbX7DT1B7N0ctbgmCo/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJhY2Nlc3Mu/Y29tL2Z1bGwvOTMz/NTI0Ni5qcGc"
    },
    {
        id: 17,
        title: "Brahmastra",
        rating: 7.0,
        genre: "Fantasy",
        year: 2022,
        certification: "UA",
        director: "Ayan Mukerji",
        cast: ["Ranbir Kapoor", "Alia Bhatt"],
        isFavorite: false,
        image: "https://shorturl.at/6bsxr"
    },
    {
        id: 18,
        title: "Animal",
        rating: 7.7,
        genre: "Action/Crime",
        year: 2023,
        certification: "A",
        director: "Sandeep Reddy Vanga",
        cast: ["Ranbir Kapoor", "Rashmika Mandanna"],
        isFavorite: false,
        image: "https://imgs.search.brave.com/QfIiDQvqtpi2Fy6t9p1eHlLifQB1NzwZtGYrLdPHk0U/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJhY2Nlc3Mu/Y29tL2Z1bGwvMTIy/NDczODEuanBn"
    },
    {
        id: 19,
        title: "Rockstar",
        rating: 8.5,
        genre: "Musical/Drama",
        year: 2011,
        certification: "UA",
        director: "Imtiaz Ali",
        cast: ["Ranbir Kapoor", "Nargis Fakhri"],
        isFavorite: false,
        image: "https://picsum.photos/300/450?random=11"
    },
    {
        id: 20,
        title: "Kabir Singh",
        rating: 7.2,
        genre: "Romance/Drama",
        year: 2019,
        certification: "A",
        director: "Sandeep Reddy Vanga",
        cast: ["Shahid Kapoor", "Kiara Advani"],
        isFavorite: false,
        image: "https://picsum.photos/300/450?random=12"
    },
    {
        id: 21,
        title: "Shershaah",
        rating: 8.4,
        genre: "Biography/War",
        year: 2021,
        certification: "UA",
        director: "Vishnuvardhan",
        cast: ["Sidharth Malhotra", "Kiara Advani"],
        isFavorite: false,
        image: "https://picsum.photos/300/450?random=13"
    },
    {
        id: 22,
        title: "Bhool Bhulaiyaa 2",
        rating: 7.0,
        genre: "Comedy/Horror",
        year: 2022,
        certification: "UA",
        director: "Anees Bazmee",
        cast: ["Kartik Aaryan", "Tabu"],
        isFavorite: false,
        image: "https://shorturl.at/Pc8oT"
    },
    {
        id: 23,
        title: "Drishyam 2",
        rating: 8.3,
        genre: "Crime/Thriller",
        year: 2022,
        certification: "UA",
        director: "Abhishek Pathak",
        cast: ["Ajay Devgn", "Tabu"],
        isFavorite: false,
        image: "https://imgs.search.brave.com/11NZOiLYVnOqa1mSty1rXJPXugKdZmcfwkLV7aYzpgU/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9taXIt/czMtY2RuLWNmLmJl/aGFuY2UubmV0L3By/b2plY3RzLzQwNC9h/ZjU3ZWIxNTczNjUw/NzkuWTNKdmNDd3pP/RE0xTERNd01EQXNN/VEE0TWl3dy5qcGc"
    },
    {
        id: 24,
        title: "Raazi",
        rating: 8.1,
        genre: "Spy/Drama",
        year: 2018,
        certification: "UA",
        director: "Meghna Gulzar",
        cast: ["Alia Bhatt", "Vicky Kaushal"],
        isFavorite: false,
        image: "https://picsum.photos/300/450?random=16"
    },
    {
        id: 25,
        title: "Andhadhun",
        rating: 8.7,
        genre: "Crime/Thriller",
        year: 2018,
        certification: "UA",
        director: "Sriram Raghavan",
        cast: ["Ayushmann Khurrana", "Tabu"],
        isFavorite: false,
        image: "https://imgs.search.brave.com/LKRmP3LcVrA_4oHKFGZUBeGK79vOTWLTTGBkh0I8oyY/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NTF3aG5oNnhILUwu/anBn"
    },
];