export const users = [
    {
        id: 1,
        name: "John Doe",
        role: "Frontend Developer",
        bio: "Passionate front-end developer with 3+ years of experience in building responsive web applications. Skilled in React, JavaScript, and CSS. Dedicated to creating user-friendly interfaces and improving user experience.",
        skills: [
            "React",
            "JavaScript",
            "CSS",
            "Node.js",
            "Express.js",
            "MongoDB",
            "Git",
            "GitHub",
            "Next.js",
        ],
        imgUrl: "https://randomuser.me/api/portraits/men/32.jpg",
        likes: 128,
    },
    {
        id: 2,
        name: "Emma Wilson",
        role: "UI/UX Designer",
        bio: "Creative UI/UX designer with a passion for crafting intuitive and visually appealing digital experiences. Experienced in Figma, Adobe XD, and user research.",
        skills: [
            "Figma",
            "Adobe XD",
            "UI Design",
            "UX Research",
            "Wireframing",
            "Prototyping",
            "Illustrator",
            "Photoshop",
        ],
        imgUrl: "https://randomuser.me/api/portraits/women/44.jpg",
        likes: 214,
    },
    {
        id: 3,
        name: "Michael Brown",
        role: "Full Stack Developer",
        bio: "Full-stack developer with 5 years of experience building scalable web applications using modern JavaScript technologies and cloud services.",
        skills: [
            "React",
            "Next.js",
            "TypeScript",
            "Node.js",
            "Express.js",
            "PostgreSQL",
            "Docker",
            "AWS",
        ],
        imgUrl: "https://randomuser.me/api/portraits/men/56.jpg",
        likes: 342,
    },
    {
        id: 4,
        name: "Sophia Martinez",
        role: "Backend Developer",
        bio: "Backend engineer focused on designing secure APIs and high-performance server-side applications. Enthusiastic about clean architecture and scalable systems.",
        skills: [
            "Node.js",
            "Express.js",
            "MongoDB",
            "Redis",
            "Docker",
            "JWT",
            "REST API",
            "GraphQL",
        ],
        imgUrl: "https://randomuser.me/api/portraits/women/68.jpg",
        likes: 186,
    },
    {
        id: 5,
        name: "David Lee",
        role: "Mobile App Developer",
        bio: "Mobile application developer specializing in cross-platform apps with React Native. Passionate about delivering smooth and responsive mobile experiences.",
        skills: [
            "React Native",
            "JavaScript",
            "TypeScript",
            "Firebase",
            "Expo",
            "Redux",
            "Git",
            "REST API",
        ],
        imgUrl: "https://randomuser.me/api/portraits/men/74.jpg",
        likes: 275,
    },
];